import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import Image from "next/image";
import bgGradient from "@/public/gradientBg.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body
  className={`bg-[url('/gradientBg.svg')] bg-[-z-1] bg-[length:300%] bg-top bg-no-repeat min-h-screen ${geistSans.className} ${geistMono.variable} antialiased overflow-auto`}
>
  <><div className="relative z-50">
<Navbar/>
</div>
  <div className="relative">{children}</div></>
  
 
</body>

    </html>
  );
}
